name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repo
    - uses: actions/checkout@v3

    # 2️⃣ Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: npm install

    # 4️⃣ Run tests (currently a placeholder, passes automatically)
    - name: Run tests
      run: npm test

    # 5️⃣ Deploy to Render
    - name: Deploy to Render
      if: success()
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        curl -X POST "https://api.render.com/deploy/srv-${RENDER_SERVICE_ID}" \
        -H "Authorization: Bearer ${RENDER_API_KEY}" \
        -H "Accept: application/json"
